### ISSUE TITLE
官网登陆不了了，请发给我新的地址，guangkai.sun@buaa.edu.cn

### ISSUE THREAD

**Issue by GuangkaiSun** [tizi12/tiziin#2]
官网登陆不了了，请发给我新的地址，guangkai.sun@buaa.edu.cn

**Comment by tizi12** [comment]
文档里面不是有的吗？ 看你收藏的那个地方

**Comment by tizi12** [comment]
https://github.com/tizi12/tiziin/blob/a/a.md
