### ISSUE TITLE
续费后好像还是用不了

### ISSUE THREAD

**Issue by cylhqs** [tizi12/tiziin#3]
![28e58f30b136837f58d5431817330c7](https://user-images.githubusercontent.com/51875629/59561640-41ad3100-9055-11e9-9a08-912562645a8e.png)

**Comment by tizi12** [comment]
这个问题注意到了，是因为到期后请求配置会被封ip，我们调整为续费清理封掉的ip，后面不会出现这个问题了

**Comment by leesper** [comment]
@tizi12 问题仍然出现，求解决啊
